Writing query
jackdavidweber/step-portfolio pull request #25
Opened 2020-06-13 00:23 UTC by jackdavidweber

Finished week 5. Successful build passes all tests.

Got everything to work, but still need to make things look nicer and more efficient

2020-06-15 17:13 UTC, augerm requested changes

2020-06-15 17:13 UTC, augerm commented on walkthroughs/week-5-tdd/project/src/main/java/com/google/sps/FindMeetingQuery.java
> +  public boolean slotPossibleDuration(MeetingRequest request, int startSlot, int endSlot){
`slotPossibleDuration` --> `slotIsPossibleDuration`

2020-06-15 17:13 UTC, augerm commented on walkthroughs/week-5-tdd/project/src/main/java/com/google/sps/FindMeetingQuery.java
> +    // Collection<String> meetingAttendees = request.getAttendees();
Remove

2020-06-15 17:13 UTC, augerm commented on walkthroughs/week-5-tdd/project/src/main/java/com/google/sps/FindMeetingQuery.java
> +  public boolean conflictIsOptionallyRelevant(Event conflict, MeetingRequest request){
`conflictIsOptionallyRelevant` --> `conflictIsRelevantForOptionalMembers`

2020-06-15 17:13 UTC, augerm commented on walkthroughs/week-5-tdd/project/src/main/java/com/google/sps/FindMeetingQuery.java
> +    Collection<TimeRange> optionsCollection;
Variable name should mention something to do with timeRanges or availability. `options` is a bit ambiguous

2020-06-15 17:13 UTC, augerm commented on walkthroughs/week-5-tdd/project/src/main/java/com/google/sps/FindMeetingQuery.java
> +    Iterator<Event> eventsIterator =  events.iterator();
Do we need to sort this?

2020-06-16 00:18 UTC, jackdavidweber commented on walkthroughs/week-5-tdd/project/src/main/java/com/google/sps/FindMeetingQuery.java
> +    Iterator<Event> eventsIterator =  events.iterator();
Yes- will work on this on Tuesday.

2020-06-16 16:32 UTC, jackdavidweber commented on walkthroughs/week-5-tdd/project/src/main/java/com/google/sps/FindMeetingQuery.java
> +    Iterator<Event> eventsIterator =  events.iterator();
@augerm done!

2020-06-17 14:46 UTC, augerm approved these changes

2020-06-18 20:34 UTC, merged